### ISSUE TITLE
Library layout need a few improvements

### ISSUE THREAD

**Issue by vladcalin** [liiight/notifiers#19]
I have noticed that there are some improvements that can be done to the repository:

- documentation should have its own directory (usually ``docs``) where to contain the RST files and the Sphinx configuration files
- there are duplicate requirements files. I suggest to group them all in a ``requirements`` directory.
- I don't think there is a need to keep the cli separated from the core library.

Cheers,
Vlad.

**Comment by liiight** [comment]
Thank you for your feedback!

1. I completely agree about docs and it's a WIP. I wanted to have some real content in the lib asap before I fully document it, but it's on its way.
2. The multiple requirement files are not duplicate, as there's regular and dev requirements with a `in` file for both, as used by `pip-tools`. As for putting then in a separate dir, I don't think it's required.
3. I disagree on the point the the CLI part should be a part of the core, as it's by definition a client of the library, and unrelated to its core logic.

I really appreciate the feedback!

**Comment by vladcalin** [comment]
2. You are right. I was not aware that the project is using `pip-tools`.
3. As you wish. I still believe that the cli should be inside the as it is tightly coupled to the core logic (it's just another api to access its functionality, that allows integration with other non-Python systems) and cannot exist on its own.

**Comment by liiight** [comment]
Let's pick this up on [gitter](https://gitter.im/notifiers/notifiers) if you wish
