### ISSUE TITLE
SMS notification (using Twilio?)

### ISSUE THREAD

**Issue by Delgan** [liiight/notifiers#30]
Hey! 

I really like your `notifiers` library. This is **exactly** what I was looking for a few weeks ago, but I did not find anything. Today, here it is, so thank you for the work!

I thought a very useful notification type would be sending SMS. I think we can do this with Twilio for example. Do you think that would be a good idea?

**Comment by liiight** [comment]
Thanks you for your kind word! Twilio is definitely planned to be supported in the near future, I'll add an issue and a milestone so you can track it

**Comment by liiight** [comment]
#31

**Comment by Delgan** [comment]
@liiight Great, thanks! 👍 

I am closing this issue then.
