### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by jsjoeio** [liiight/notifiers#396]
Hey, just wanted to come by and say thank you for notifiers! ♥️

I wrote a script to automate monthly Venmo requests ([monthly-venmo](https://github.com/jsjoeio/monthly-venmo)) and notifiers made it super easy for me to add Telegram notifications to my project. 

Now my Telegram messages me when my script runs, thanks to you!

Cheers! 🎉

**Comment by jsjoeio** [comment]
(Obviously, feel free to close after you read!)

**Comment by liiight** [comment]
Thank you, it really means a lot to get this feedback. Thank you for the twitter shoutout as well, highly appreciated 🙏
