### ISSUE TITLE
Cannot use Gmail - two factor authorization required

### ISSUE THREAD

**Issue by JustAPhrog** [liiight/notifiers#408]
**Describe the bug**
I'm trying to use `gmail` to push notification but my account has 2-factor authentication and error apears:

    ERROR: Notification errors: (530, b'5.7.0 Authentication Required. Learn more at\n5.7.0  https://support.google.com/mail/?p=WantAuthError w29sm134325lfn.97 - gsmtp', '<user@gmail.com>')

**To Reproduce**
````bash
notifiers gmail notify --from "user@gmail.com" --to "user2@gmail.com" --subject "Test aa" --username "<user>@gmail.com" --password "<pass>" --tls "Hello!"
````

**Expected behavior**
User2 receive email: "Test aa" with message "Hello!"

**Additional context**
Python version: 3.8.10
OS: Ubuntu 20.04 in WSL Win10 (build 19042)
Notifiers: 1.2.1

**Comment by liiight** [comment]
You need to create an app password for it to work when using 2FA: https://support.google.com/mail/answer/185833?hl=en-GB
