### ISSUE TITLE
sdist missing from 1.3.0 release

### ISSUE THREAD

**Issue by dtrodrigues** [liiight/notifiers#413]
https://pypi.org/project/notifiers/1.3.0/#files is missing an sdist. One was present for 1.2.1: https://files.pythonhosted.org/packages/4f/36/4c300f55949b9be84284d51253ae48d564dc2c4f2bffb94f26c8c1485f07/notifiers-1.2.1.tar.gz

**Comment by liiight** [comment]
Fixed and released in 1.3.1. Sorry about that, I'm dusting off some parts after a long while
