### ISSUE TITLE
'from' can't be used as a keyword argument in the email notifier. 

### ISSUE THREAD

**Issue by astoddard** [liiight/notifiers#49]
Trying to use the optional 'from' argument as a keyword argument to the notify method for the email notifier is a syntax error when used from code (it works just fine from the CLI interface).

Maybe 'from' should be renamed to avoid the problem.  A work-around is calling notify with dictionary unpacking. But that should probably be documented.

`>>> from notifiers import get_notfier`
`>>> p = get_notifier('email')`
`<Provider:[Email]>`
`>>> p.notify(to='someone@example.com', message='Will not work', from='sender@example.com')`

 `File "<stdin>", line 1`
 ` p.notify(to='someone@example.com', message='Will not work', from='sender@example.com')`
`...............................................................^`
`SyntaxError: invalid syntax`

`>>> p.notify(**{'to':'someone@example.com', 'message':'Will work', 'from':'sender@example.com'})`
`<Response,provider=Email,status=Success>`

**Comment by liiight** [comment]
Right, `from` is a reserved word. You can get around that by passing a dict but I'll change it to `from_`

**Comment by astoddard** [comment]
maybe 'email_from' would be better? That way it doesn't look magical.

**Comment by liiight** [comment]
Dunno, that's a little too much unlike the others, isn't it?

**Comment by liiight** [comment]
dunno, that'll make cli usage much more clunky.

**Comment by astoddard** [comment]
True, but 'from_' is also really ugly on the command line.  That suggests allowing aliases for arguments, and at that point you can alias more than one and keep the nicer command line interface with a consistent code based one too. 

I'm actually fine with documenting the need to call p.notify with a dict when using `from` as an argument in code and leaving it at that.

**Comment by ocurero** [comment]
+1 for "from_"

SQLAlchemy has the same "problem" with the "OR" SQL expression and they solved it using a [underscore for or_](http://docs.sqlalchemy.org/en/latest/core/sqlelement.html#sqlalchemy.sql.expression.or_). I think is pretty straightforward to understand.

**Comment by liiight** [comment]
I kept both, so you can still send `from` via dict or from cli, and use `from_` when sending key directly.
