### ISSUE TITLE
Support for Zulip

### ISSUE THREAD

**Issue by ralienpp** [liiight/notifiers#61]
Zulip, http://zulip.org, is an enterprise chat solution that can be used in a self-hosted fashion (available as free/open-source). One could see it as a better Slack, and I believe `notifiers` could benefit from adding compatibility with it.

I am using it with Slack at the moment, but some of the automated notifications arrive often and "eat the quota" very fast.

**Comment by liiight** [comment]
yeah, zulip has been on my radar, forgot to update it in the "future" section.
